# @package _global_

defaults:
  - /defaults/default_runtime
  - /tasks/segmentation3d/ptv3/encoder_base
  - /tasks/detection3d/ptv3/bev_neck
  - _self_

dataset: ???

grid_size: ???
point_cloud_range: ???

train_sweeps_num: 1
val_sweeps_num: 1

datamodule:
  _target_: ???
  data_root: ${dataset.data_root}
  train_ann_file: ${datamodule.data_root}/info/detection3d/t4dataset_j6gen2_base_infos_train.pkl
  val_ann_file: ${datamodule.data_root}/info/detection3d/t4dataset_j6gen2_base_infos_val.pkl
  test_ann_file: ${datamodule.data_root}/info/detection3d/t4dataset_j6gen2_base_infos_val.pkl
  class_names: ${dataset.detection3d.class_names}
  name_mapping: ${dataset.detection3d.name_mapping}
  train_frame_sampling:
    repeat_sampling_factor: 0.30
    object_bev_range: ???
    low_pedestrian_height_threshold: 1.5
    low_pedestrian_bev_range: [-50.0, -50.0, 50.0, 50.0]
  collation_map:
    coord: concat
    feat: concat
    grid_coord: concat
    gt_boxes: list
    gt_labels: list
    gt_num_points: list

model:
  _target_: autoware_ml.models.detection3d.ptv3.PTv3DetectionModel
  export_output_names: ???
  freeze_encoder: false
  grid_size: ${grid_size}
  point_cloud_range: ${point_cloud_range}
  metrics: ${dataset.detection3d.metrics}
  bbox_head: ???
  optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 0.0001
    weight_decay: 0.01
  scheduler:
    _target_: autoware_ml.utils.schedulers.cyclic_cosine_annealing.CyclicCosineAnnealingLR
    _partial_: true
    warmup_epochs: 8
    decay_epochs: 22
    max_lr_factor: 10.0
    min_lr_factor: 0.0001

trainer:
  max_epochs: 30
  precision: 32-true
  gradient_clip_val: 5.0
  gradient_clip_algorithm: norm

callbacks:
  model_checkpoint:
    monitor: val/pytorch/det3d/mAP
    mode: max
  early_stopping:
    monitor: val/pytorch/det3d/mAP
    patience: 20
    mode: max

deploy:
  onnx:
    enabled: true
    opset_version: 17
    dynamo: false
    do_constant_folding: false
    modules:
      ptv3_encoder:
        output_names: [point_feat_0, point_feat_1, point_feat_2, point_feat_3, point_feat_4]
        metainfo:
          point_cloud_range: ${point_cloud_range}
          voxel_size: ["${grid_size}", "${grid_size}", "${grid_size}"]
          serialization_orders: [z, z-trans]
          pooling_strides: ${model.encoder.stride}
          enc_channels: ${model.encoder.enc_channels}
      ptv3_det3d_head:
        output_names: ${model.export_output_names}
        metainfo:
          bbox_voxel_size: ${model.bbox_head.bbox_coder.voxel_size}
          has_twist: ${model.bbox_head.use_velocity}
          num_proposals: ${model.bbox_head.num_proposals}
          post_center_range: ${model.bbox_head.bbox_coder.post_center_range}
          class_names: ${dataset.detection3d.class_names}
  tensorrt:
    enabled: false
