# @package _global_
defaults:
  - /tasks/detection3d/bevfusion/base
  - /datasets/t4dataset/detection3d
  - /datasets/t4dataset/lidar
  - /datasets/t4dataset/camera
  - _self_

batch_size: 8
num_workers: 8

dataset: ${t4dataset}

point_cloud_range: [-122.4, -122.4, -3.0, 122.4, 122.4, 5.0]
voxel_size: [0.17, 0.17, 0.2]
out_size_factor: 8
max_time_lag: 0.2
bev_voxel_size: [0.68, 0.68]
image_size: [384, 768]

datamodule:
  collation_map:
    img: list
    camera_intrinsics: list
    lidar2cam: list
    lidar2img: list
    img_aug_matrix: list
  _target_: autoware_ml.datamodule.t4dataset.multiview_detection3d.T4MultiviewDetection3DDataModule
  data_root: ${dataset.data_root}
  train_ann_file: info/detection3d/t4dataset_j6gen2_base_infos_train.pkl
  val_ann_file: info/detection3d/t4dataset_j6gen2_base_infos_val.pkl
  test_ann_file: info/detection3d/t4dataset_j6gen2_base_infos_val.pkl
  class_names: ${dataset.detection3d.class_names}
  camera_order: ${dataset.camera.camera_order}
  name_mapping: ${dataset.detection3d.name_mapping}
  train_dataloader_cfg:
    batch_size: ${batch_size}
    num_workers: ${num_workers}
    shuffle: true
  val_dataloader_cfg:
    batch_size: ${batch_size}
    num_workers: ${num_workers}
  test_dataloader_cfg:
    batch_size: ${batch_size}
    num_workers: ${num_workers}
  train_transforms:
    _target_: autoware_ml.transforms.base.TransformsCompose
    pipeline:
      - _target_: autoware_ml.transforms.boxes3d.merge.MergeObjects3D
        merge_objects: ${dataset.detection3d.merge_objects}
        name_mapping: ${dataset.detection3d.name_mapping}
      - _target_: autoware_ml.transforms.boxes3d.loading.LoadAnnotations3D
        name_mapping: ${dataset.detection3d.name_mapping}
        filter_attributes: ${dataset.detection3d.filter_attributes}
        use_valid_flag: ${dataset.detection3d.use_valid_flag}
      - _target_: autoware_ml.transforms.camera.loading.LoadMultiViewImagesFromFiles
      - _target_: autoware_ml.transforms.point_cloud.sweeps.LoadPointsFromMultiSweeps
        sweeps_num: 2
        load_dim: 5
        use_dim: [0, 1, 2, 3, 4]
        time_dim: 4
        pad_empty_sweeps: true
        remove_close: true
      - _target_: autoware_ml.transforms.camera_lidar.camera_lidar.ImageAug3D
        final_dim: ${image_size}
        resize_lim: [0.29, 0.35]
        bot_pct_lim: [0.0, 0.0]
        rand_flip: true
        rot_lim: [-5.4, 5.4]
        training: true
      - _target_: autoware_ml.transforms.camera_lidar.geometry.GlobalRotScaleTrans
        rot_range: [-0.78539816, 0.78539816]
        scale_ratio_range: [0.95, 1.05]
      - _target_: autoware_ml.transforms.camera_lidar.geometry.RandomFlip3D
        flip_ratio_bev_horizontal: 0.5
        flip_ratio_bev_vertical: 0.5
      - _target_: autoware_ml.transforms.point_cloud.crop.PointsRangeFilter
        point_cloud_range: ${point_cloud_range}
      - _target_: autoware_ml.transforms.boxes3d.filters.ObjectRangeFilter
        point_cloud_range: ${point_cloud_range}
      - _target_: autoware_ml.transforms.boxes3d.filters.ObjectRangeMinPointsFilter
        range_radius: [0.0, 60.0]
        min_num_points: ${dataset.detection3d.train_min_points_near}
      - _target_: autoware_ml.transforms.boxes3d.filters.ObjectRangeMinPointsFilter
        range_radius: [60.0, 130.0]
        min_num_points: ${dataset.detection3d.train_min_points_far}
      - _target_: autoware_ml.transforms.point_cloud.sampling.PointShuffle
  val_transforms:
    _target_: autoware_ml.transforms.base.TransformsCompose
    pipeline:
      - _target_: autoware_ml.transforms.boxes3d.merge.MergeObjects3D
        merge_objects: ${dataset.detection3d.merge_objects}
        name_mapping: ${dataset.detection3d.name_mapping}
      - _target_: autoware_ml.transforms.boxes3d.loading.LoadAnnotations3D
        name_mapping: ${dataset.detection3d.name_mapping}
        filter_attributes: ${dataset.detection3d.filter_attributes}
        use_valid_flag: ${dataset.detection3d.use_valid_flag}
      - _target_: autoware_ml.transforms.camera.loading.LoadMultiViewImagesFromFiles
      - _target_: autoware_ml.transforms.point_cloud.sweeps.LoadPointsFromMultiSweeps
        sweeps_num: 2
        load_dim: 5
        use_dim: [0, 1, 2, 3, 4]
        time_dim: 4
        pad_empty_sweeps: true
        remove_close: true
      - _target_: autoware_ml.transforms.camera_lidar.camera_lidar.ImageAug3D
        final_dim: ${image_size}
        resize_lim: [0.32, 0.32]
        bot_pct_lim: [0.0, 0.0]
        rand_flip: false
        rot_lim: [0.0, 0.0]
        training: false
      - _target_: autoware_ml.transforms.point_cloud.crop.PointsRangeFilter
        point_cloud_range: ${point_cloud_range}
  test_transforms: ${datamodule.val_transforms}
  predict_transforms:
    _target_: autoware_ml.transforms.base.TransformsCompose
    pipeline:
      - _target_: autoware_ml.transforms.camera.loading.LoadMultiViewImagesFromFiles
      - _target_: autoware_ml.transforms.point_cloud.sweeps.LoadPointsFromMultiSweeps
        sweeps_num: 2
        load_dim: 5
        use_dim: [0, 1, 2, 3, 4]
        time_dim: 4
        pad_empty_sweeps: true
        remove_close: true
      - _target_: autoware_ml.transforms.camera_lidar.camera_lidar.ImageAug3D
        final_dim: ${image_size}
        resize_lim: [0.32, 0.32]
        bot_pct_lim: [0.0, 0.0]
        rand_flip: false
        rot_lim: [0.0, 0.0]
        training: false
      - _target_: autoware_ml.transforms.point_cloud.crop.PointsRangeFilter
        point_cloud_range: ${point_cloud_range}

model:
  pts_middle_encoder:
    sparse_shape: [1440, 1440, 41]
    dense_output_shapes: [180, 180, 2]
  view_transform:
    feature_size: [48, 96]
    dbound: [1.0, 130.0, 1.0]
  bbox_head:
    num_proposals: 500
    class_names: ${dataset.detection3d.class_names}
    num_classes: ${dataset.detection3d.num_classes}
    dense_heatmap_pooling_classes: [car, truck, bus, barrier]
    nms_type: circle
    nms_min_radius: 0.25
    nms_groups:
      - class_names: [car, truck, bus]
        nms_radius: 0.25
        post_max_size: 300
      - class_names: [bicycle]
        nms_radius: 0.0
        post_max_size: 50
      - class_names: [pedestrian]
        nms_radius: 0.0
        post_max_size: 100
      - class_names: [traffic_cone]
        nms_radius: 0.0
        post_max_size: 100
      - class_names: [barrier]
        nms_radius: 0.0
        post_max_size: 50
    bbox_coder:
      post_center_range: [-200.0, -200.0, -10.0, 200.0, 200.0, 10.0]
      score_threshold: [0.015, 0.010, 0.010, 0.020, 0.030, 0.040, 0.020]
