_target_: autoware_ml.datamodule.multi_task.multi_task_data_module.MultiTaskDataModule
_convert_: all

defaults:
  - splitter: default_scenario_splitter
  - dataloader@train_dataloader: default_dataloader
  - dataloader@validation_dataloader: default_dataloader
  - dataloader@test_dataloader: default_dataloader
  - dataloader@predict_dataloader: default_dataloader
  - t4dataset/datasets@train_dataset: default_segmentation3d_train_dataset
  - t4dataset/datasets@test_dataset: default_segmentation3d_test_dataset
  - t4dataset/datasets@validation_dataset: default_segmentation3d_val_dataset
  - t4dataset/datasets@predict_dataset: default_segmentation3d_predict_dataset
