_target_: autoware_ml.datamodule.multi_task.t4dataset.multi_task_t4dataset.MultiTaskT4Dataset
_convert_: all

defaults:
  - detection3d@dataset_tasks.detection3d: default_detection3d
  - ../../transforms@transforms: default_train_transforms

database_root_path: ${database.root_path}

# Always None since we run splitter in the process
dataset_records_dataframe: null

# When number of 3D GT bboxes in a scenario exceeds this number, we will select the first
# `max_num_3d_gt_bboxes` bboxes and ignore the rest. 500 is usually a
# common number of bboxes to include all 3D GT bboxes in a scenario.
max_num_3d_gt_bboxes: 500

split_type:
  _target_: autoware_ml.types.dataset.SplitType
  _convert_: all
  _args_: [train]
