# @package _global_

defaults:
  - modules/callbacks
  - modules/data_preprocessing
  - modules/datamodule
  - modules/deploy
  - modules/logger
  - modules/model
  - modules/paths
  - modules/quantization
  - modules/run
  - modules/trainer
