_target_: autoware_ml.databases.t4dataset.t4dataset.T4Dataset
_convert_: all

version: T4Dataset-j6gen2_base-v1.0.0
# Root path of actual annotation files
root_path: ${data_root_path}/t4dataset/

# Caches
cache_path: ${cache_root_path}/detection3d/
# Prefix name of the cache file, it will be <cache_file_prefix_name>_<database_hash>.parquet
cache_file_prefix_name: database

# Read each database into their corresponding scenarios, it will run evaluation/visualization on each scenario
defaults:
  - t4dataset/database_task_configs@database_task_configs.detection3d: detection3d/default_detection3d_task
  - t4dataset/box3d_pipelines@box3d_pipelines: default_box3d_pipelines
  - t4dataset/scenarios@scenarios.db_j6gen2_base: detection3d/db_j6gen2_base
  - t4dataset/scenarios@scenarios.db_j6gen2: detection3d/db_j6gen2
  - t4dataset/scenarios@scenarios.db_largebus: detection3d/db_largebus
  - _self_

# Number of features in the lidar pointcloud
lidar_pointcloud_num_features: 5

# Processor settings
num_workers: 16
