- _target_: autoware_ml.metrics.detection3d.suite.Detection3DMetricSuite
  components:
    - { _target_: autoware_ml.metrics.detection3d.box_counts.BoxCounts, stages: [val, test] }
    - { _target_: autoware_ml.metrics.detection3d.mean_ap.MeanAP, stages: [val, test] }
    - { _target_: autoware_ml.metrics.detection3d.heading_ap.HeadingAP, stages: [test] }
    - { _target_: autoware_ml.metrics.detection3d.nds.Nds, stages: [test] }
    - { _target_: autoware_ml.metrics.detection3d.tp_errors.TpErrors, stages: [test] }
  class_names: ${database.database_task_configs.detection3d.label_names}
  thresholds: [0.5, 1.0, 2.0, 4.0]
  min_num_points: 2
  eval_class_range: ${eval_class_range}
  ranges: ${metric_ranges}
