# @package _global_
defaults:
  - /defaults/default_runtime
  - /tasks/segmentation3d/ptv3/encoder_base
  - /tasks/segmentation3d/ptv3/seg_head_base
  - /tasks/detection3d/ptv3/bev_neck
  - _self_

dataset: ???

num_classes: ${dataset.detection3d.num_classes}

point_cloud_range: ???
grid_size: ???
head_voxel_size: ???

num_proposals: ???

datamodule:
  collation_map:
    coord: concat
    feat: concat
    grid_coord: concat
    segment: concat
    origin_segment: concat
    origin_coord: concat
    inverse: index_concat
    gt_boxes: list
    gt_labels: list
  data_root: ${dataset.data_root}
  class_names: ${dataset.detection3d.class_names}
  name_mapping: ${dataset.detection3d.name_mapping}

model:
  _target_: autoware_ml.models.multi.ptv3_segdet.PTv3SegDetModel
  bbox_head:
    _target_: autoware_ml.models.detection3d.heads.transfusion.TransFusionHead
    num_proposals: ${num_proposals}
    auxiliary: true
    in_channels: 128
    hidden_channel: 128
    num_classes: ${num_classes}
    class_names: ${dataset.detection3d.class_names}
    dense_heatmap_pooling_classes: [car, truck, bus]
    num_decoder_layers: 1
    num_heads: 8
    feedforward_channels: 256
    common_heads:
      center: [2, 2]
      height: [1, 2]
      dim: [3, 2]
      rot: [2, 2]
    bbox_coder:
      _target_: autoware_ml.models.detection3d.task_modules.bbox_coders.TransFusionBBoxCoder
      pc_range: ${point_cloud_range}
      voxel_size: ${head_voxel_size}
      out_size_factor: 1
      post_center_range: ???
      score_threshold: 0.0
      code_size: 8
    assigner:
      _target_: autoware_ml.models.detection3d.task_modules.assigners.HungarianAssigner3D
      cls_cost:
        _target_: autoware_ml.models.detection3d.task_modules.match_costs.ClassificationCost
        weight: 0.15
        alpha: 0.25
        gamma: 2.0
      reg_cost:
        _target_: autoware_ml.models.detection3d.task_modules.match_costs.BBoxBEVL1Cost
        weight: 0.25
      iou_cost:
        _target_: autoware_ml.models.detection3d.task_modules.match_costs.IoU3DCost
        weight: 0.25
    point_cloud_range: ${point_cloud_range}
    voxel_size: ${head_voxel_size}
    out_size_factor: 1
    code_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    min_radius: 2
    gaussian_overlap: 0.1
    score_threshold: 0.1
    post_max_size: 100
    nms_min_radius: ???
    loss_cls_weight: 1.0
    loss_bbox_weight: 0.25
    loss_heatmap_weight: 1.0
    heatmap_target: oriented
    heatmap_init_bias: -2.19
    nms_kernel_size: 3
    use_velocity: false
  segmentation_loss_weight: 1.0
  detection_loss_weight: 1.0
  metrics: ${merge_lists:${dataset.detection3d.metrics},${dataset.segmentation3d.metrics}}
  export_output_names:
    [
      pred_labels,
      pred_probs,
      dense_heatmap,
      query_heatmap_score,
      query_labels,
      heatmap,
      center,
      height,
      dim,
      rot,
    ]
  grid_size: ${grid_size}
  point_cloud_range: ${point_cloud_range}
  optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 0.0001
    weight_decay: 0.01
  optimizer_group_overrides:
    encoder_block:
      lr: 0.00002
    encoder_default:
      lr: 0.00005
    seg3d_head:
      lr: 0.00005
  scheduler:
    _target_: autoware_ml.utils.schedulers.cyclic_cosine_annealing.CyclicCosineAnnealingLR
    _partial_: true
    warmup_epochs: 12
    decay_epochs: 88
    max_lr_factor: 10.0
    min_lr_factor: 0.0001

trainer:
  max_epochs: 100
  precision: 32-true
  gradient_clip_val: 5.0
  gradient_clip_algorithm: norm

callbacks:
  early_stopping:
    patience: 30

deploy:
  onnx:
    enabled: true
    opset_version: 19
    dynamo: false
    do_constant_folding: false
    modules:
      ptv3_encoder:
        output_names: [point_feat_0, point_feat_1, point_feat_2, point_feat_3, point_feat_4]
        metainfo:
          point_cloud_range: ${point_cloud_range}
          voxel_size: ["${grid_size}", "${grid_size}", "${grid_size}"]
          serialization_orders: [z, z-trans]
          pooling_strides: ${model.encoder.stride}
          enc_channels: ${model.encoder.enc_channels}
      ptv3_seg3d_head:
        output_names: [pred_labels, pred_probs]
        metainfo:
          dec_depths: ${model.seg3d_head.dec_depths}
          class_names: ${seg_class_names:${dataset.segmentation3d.class_mapping}, ${dataset.segmentation3d.num_classes}}
      ptv3_det3d_head:
        output_names: [dense_heatmap, query_heatmap_score, query_labels, heatmap, center, height, dim, rot]
        metainfo:
          bbox_voxel_size: ${model.bbox_head.bbox_coder.voxel_size}
          has_twist: ${model.bbox_head.use_velocity}
          num_proposals: ${model.bbox_head.num_proposals}
          post_center_range: ${model.bbox_head.bbox_coder.post_center_range}
          class_names: ${dataset.detection3d.class_names}
        modify_graph:
          _target_: autoware_ml.utils.onnx_modifiers.TransHeadTensorRTModifier
          k: ${num_proposals}
          topk_node_name_substring: /bbox_head/TopK
          attention_node_name_substring: /bbox_head/decoder
  tensorrt:
    enabled: false
