_target_: autoware_ml.transforms.multi_task.base.MultiTaskTransformsCompose
_convert_: all

pipeline:
  - _target_: autoware_ml.transforms.multi_task.point_cloud.loading.LoadPointsFromFile
    _convert_: all

    load_dim: ${database.lidar_pointcloud_num_features}
    use_dim: [0, 1, 2, 3] # Refer PointFieldIndex for the name of each dimensionality, [x, y, z, intensity]
    bev_remove_radius: 0.0

  - _target_: autoware_ml.transforms.multi_task.point_cloud.loading.LoadMultiSweepPointsFromFile
    _convert_: all

    sweeps_num: 1
    bev_remove_radius: 1.0
    test_mode: false
    use_timestamp_difference: true
    load_dim: ${database.lidar_pointcloud_num_features}
    use_dim: [0, 1, 2, 3] # Refer PointFieldIndex for the name of each dimensionality, [x, y, z, intensity]

  - _target_: autoware_ml.transforms.multi_task.point_cloud.geometry.GlobalRotScaleTrans
    _convert_: all

    # In radians, the range of rotation angles for random rotation around the Z-axis.
    # The range is specified as [min_angle, max_angle].
    yaw_rot_range: [-0.78539816, 0.78539816]
    # The range of scale factors for random scaling.
    scale_ratio_range: [0.95, 1.05]
    # The standard deviation for Gaussian translation noise.
    translation_std: [0.5, 0.5, 0.2]

  - _target_: autoware_ml.transforms.multi_task.point_cloud.geometry.GlobalBEVRandomFlip
    _convert_: all

    horizontal_flip_ratio: 0.5
    vertical_flip_ratio: 0.5

  - _target_: autoware_ml.transforms.multi_task.point_cloud.geometry.PointsRangeFilter
    _convert_: all

    points_range: ${point_cloud_range}

  - _target_: autoware_ml.transforms.multi_task.point_cloud.geometry.PointsRandomShuffle
    _convert_: all

  - _target_: autoware_ml.transforms.multi_task.bboxes_3d.loading.BBoxesLabelNameFilter
    _convert_: all

    label_names_to_keep: ${database.database_task_configs.detection3d.label_names}

  - _target_: autoware_ml.transforms.multi_task.bboxes_3d.geometry.BBoxesBEVDistanceFilter
    _convert_: all

    bev_range:
      - ${point_cloud_range.0}
      - ${point_cloud_range.1}
      - ${point_cloud_range.3}
      - ${point_cloud_range.4}

  # Order matters, it first filters bboxes within the default meters with less than 2 points.
  # Then it filters bboxes within 60 meters with less than 3 points
  - _target_: autoware_ml.transforms.multi_task.bboxes_3d.geometry.BBoxesMinPointsFilter
    _convert_: all

    min_points: 2
    bev_range:
      - ${point_cloud_range.0}
      - ${point_cloud_range.1}
      - ${point_cloud_range.3}
      - ${point_cloud_range.4}

  - _target_: autoware_ml.transforms.multi_task.bboxes_3d.geometry.BBoxesMinPointsFilter
    _convert_: all

    min_points: 3
    bev_range: [-60.0, -60.0, 60.0, 60.0]

  - _target_: autoware_ml.transforms.multi_task.bboxes_3d.loading.BBoxesAttributeFilter
    _convert_: all

    attributes_to_filter:
      bicycle:
        - vehicle_state.parked
        - cycle_state.without_rider
        - motorcycle_state.without_rider
