_target_: autoware_ml.transforms.multi_task.base.MultiTaskTransformsCompose
_convert_: all

pipeline:
  - _target_: autoware_ml.transforms.multi_task.point_cloud.loading.LoadPointsFromFile
    _convert_: all

    load_dim: ${database.lidar_pointcloud_num_features}
    use_dim: [0, 1, 2, 3]
    bev_remove_radius: 0.0

  - _target_: autoware_ml.transforms.multi_task.point_cloud.loading.LoadMultiSweepPointsFromFile
    _convert_: all

    sweeps_num: 2
    bev_remove_radius: 1.0
    test_mode: true
    use_timestamp_difference: true
    load_dim: ${database.lidar_pointcloud_num_features}
    use_dim: [0, 1, 2, 3] # Refer PointFieldIndex for the name of each dimensionality, [x, y, z, intensity]

  - _target_: autoware_ml.transforms.multi_task.point_cloud.geometry.PointsRangeFilter
    _convert_: all

    points_range: ${point_cloud_range}

  - _target_: autoware_ml.transforms.multi_task.bboxes_3d.loading.BBoxesLabelNameFilter
    _convert_: all

    label_names_to_keep: ${database.database_task_configs.detection3d.label_names}

  - _target_: autoware_ml.transforms.multi_task.bboxes_3d.loading.BBoxesAttributeFilter
    _convert_: all

    attributes_to_filter:
      bicycle:
        - vehicle_state.parked
        - cycle_state.without_rider
        - motorcycle_state.without_rider
