car: car
vehicle.car: car
police_car: car
vehicle.emergency (ambulance & police): car
vehicle.ambulance: car  # Define vehicle.ambulance as car since vehicle.emergency (ambulance & police) is defined as car
vehicle.police: car
forklift: car
ambulance: car
kart: car
other_vehicle: car

truck: truck
vehicle.truck: truck
vehicle.construction: truck
vehicle.fire: truck
fire_truck: truck
tractor: truck
tractor_unit: truck
construction_vehicle: truck

trailer: trailer
vehicle.trailer: trailer
semi_trailer: trailer

motorcycle: bicycle
vehicle.motorcycle: bicycle
vehicle.bicycle: bicycle
bicycle: bicycle

bus: bus
vehicle.bus (bendy & rigid): bus
vehicle.bus: bus

pedestrian: pedestrian
pedestrian.adult: pedestrian
pedestrian.child: pedestrian
pedestrian.construction_worker: pedestrian
pedestrian.personal_mobility: pedestrian
pedestrian.police_officer: pedestrian
pedestrian.stroller: pedestrian
pedestrian.wheelchair: pedestrian
police_officer: pedestrian
construction_worker: pedestrian
stroller: pedestrian
wheelchair: pedestrian
personal_mobility: pedestrian
other_pedestrian: pedestrian

movable_object.barrier: barrier
movable_object.debris: barrier
movable_object.pushable_pullable: barrier
barrier: barrier
construction_sign: barrier
construction sign: barrier

movable_object.trafficcone: traffic_cone
movable_object.traffic_cone: traffic_cone
traffic_cone: traffic_cone
trafficcone: traffic_cone

animal: animal
static_object.bicycle_rack: bicycle_rack
static_object.bicycle rack: bicycle_rack
static_object.bollard: bollard

train: train
